<?php
$infos = file_exists('./##.php')?include('./##.php'):array();
return array_merge(array(
	/*忽略项*/
	'admin_actions' => array(	/*后台操作*/
		'login'				=> '后台登录',
		'log'				=> '日志管理',
		'config'			=> '配置',
		'set_acl'			=> '前台权限分配',
		'set_member_acl'	=> '会员前台权限分配',
		'set_admin_acl'		=> '后台权限分配',
		'memcache'			=> 'memcache管理',
		'db_slave'			=> 'MYSQL附加服务器配置',
		'menu'				=> '后台菜单管理',
		'navigation_menu_list' 	=> '头部导航管理',
		'member_menu'		=> '会员中心菜单管理',
		'system_list'		=> '系统列表',
		'module_list'		=> '模块列表',
		'plugin_list'		=> '插件列表',
		'plugin'			=> '插件配置',
		'install_system'	=> '安装系统',
		'uninstall_system'	=> '卸载系统',
		'install_module'	=> '安装模块',
		'uninstall_module'	=> '卸载模块',
		'install_plugin'	=> '安装插件',
		'uninstall_plugin'	=> '卸载插件',
		'cache' 			=> '更新缓存',
		'cache_label' 		=> '更新分站缓存',
		'phpinfo' 			=> '查看服务器信息',
		'template_system' 	=> '模板管理',
		'base_config' 		=> '基本配置',
		'global_config' 	=> '全局配置',
		'env' 				=> '系统环境检测',
		'dirfile' 			=> '文件权限检测',
		'tables' 			=> '升级完整性检测',
		'plant_config' 		=> '数据运维总览配置',
		'reg_config' 		=> '注册配置',
		'homepage_config' 	=> '个人主页配置',
		'stop_ip' 			=> 'IP黑名单',
		'allow_ip' 			=> 'IP白名单',
		'word_filter' 		=> '词语过滤',
		'word_censor_config'=> '大数据内容扫描检测设置',
		'word_censor' 		=> '大数据内容扫描检测',
		'word_scan_config'=> '内容体检扫描设置',
		'word_scan' 		=> '内容体检扫描',
		'connection_flood' 	=> '防止CC攻击',		
		'area' 				=> '地区管理',
		'main'				=> '后台初始页',
		'index'				=> '后台上与左菜单',
		'font_admin_menu'	=> '前台便捷管理菜单',
		'genrate_html'		=> '静态首页',
		'reflash_index'		=> '更新首页',
	),
	'admin_actions_map' => array(
		'base_config' 		=> '基本配置',
		'global_config' 	=> '全局配置',
		'env' 				=> '系统环境检测',
		'dirfile' 			=> '文件权限检测',
		'tables' 			=> '升级完整性检测',
		'plant_config' 		=> '数据运维总览配置',
		'log'				=> '日志管理',		
		'set_acl'			=> '前台权限分配',
		'set_admin_acl'		=> '后台权限分配',
		'memcache'			=> 'memcache管理',
		'db_slave'			=> '附加服务器配置',
		'menu_list'				=> '后台菜单管理',
		'navigation_menu_list' 	=> '头部导航管理',
		'member_menu_list'		=> '会员中心菜单管理',
		'system_list'		=> '系统列表',
		'module_list'		=> '模块列表',
		'plugin_list'		=> '插件列表',		
		'template_system' 	=> '模板管理',		
		'reg_config' 		=> '注册配置',
		'stop_ip' 			=> 'IP黑名单',
		'allow_ip' 			=> 'IP白名单',
		'word_filter' 		=> '词语过滤',
		'word_censor_config'=> '大数据内容扫描检测设置',
		'word_censor' 		=> '大数据内容扫描检测',
		'connection_flood' 	=> '防止CC攻击',
		'area' 				=> '地区管理',
		'genrate_html'		=> '静态首页',
		'reflash_index'		=> '更新首页',
		'cache' 			=> '更新缓存',
		'cache_label' 		=> '更新分站缓存',
	),
	/*前台*/
	'actions' => array(	
	),
	/*忽略项*/
	
	
	/*手动添加项*/
	
	/*编码转换函数集*/
	'encode_conv_functions' => array(
		'default' => '',
		'mb_convert_encoding' => 'mb_convert_encoding',
		'iconv' => 'iconv',
	),
    'template' => 'default',
    'credit' => '1',
    'next_crontab' => P8_TIME,
	
	
),(array)$infos);
