<?php
return array(
	//忽略项
	'alias' => '主站内容模块',
	'class' => 'P8_CMS_Item',
	'controller_class' => 'P8_CMS_Item_Controller',
	
	'admin_actions' => array(
		'config' => '模块配置',
		//'verify_acl' => '分级审核',
		
		'add' => '添加',
		'verify_first' => '初审',
		'verify' => '终审',
		'move' => '移动内容',
		'clone' => '签发内容',
		'list' => '列表',
		'update' => '修改',
		'delete' => '删除',
		'set_member_acl' => '设置会员前台权限',
		'level' => '设置内容权重',
		'score' => '设置内容评分',
		'setviews' => '设置浏览量',		
		'list_to_html' => '列表页静态',
		'view_to_html' => '内容页静态',
		'set_lan'      => '内容局域网化设置',
		'attribute' => '设置内容属性',
		'attribute_acl' => '内容属性分配权限',
		'label' => '标签管理',		
		'list_order' => '置顶或下沉内容',		
		'create_time' => '设置发布时间',
		'filter_word' => '忽略系统敏感词检测',
		'content_censor' => '忽略大数据内容检测',	
		'set_acl' => '分配权限',		
		'mood' => '表情管理',		
		'spider' => '采集入库',
		'tag' => 'Tag(标签)管理',
		'report' => '统计报告',
		'cluster_push' => '推送数据',
		'push_status' => '推送数据状态',
		'download' => '导出数据',
		'comment' => '评论管理',
		'verify_comment' => '审核评论',
		'delete_comment' => '删除评论',
		'delete_html' => '删除超年限静态页面',
	),
	'admin_actions_map' => array(		
		'config' => '模块配置',		
		'add' => '添加内容',		
		'list' => '内容列表',
		'comment' => '评论/订单管理',		
		'list_to_html' => '列表页静态',
		'view_to_html' => '内容页静态',		
		'mood' => '表情管理',		
		'spider' => '采集入库',
		'tag' => 'Tag(标签)管理',		
		'report' => '统计报告',
		'push_status' => '推送数据状态',
	),
	'actions' => array(
		'list_to_html' => '列表页静态',
		'genrate_html' => '静态首页',
		'reflash_index' => '更新首页',
		'list' => '查看列表',
		'view' => '查看内容',		
		'add' => '发表内容',
		'update' => '修改',
		'delete' => '删除',
        'verify_first' => '初审',
        'verify' => '终审',
		'autoverify' => '自动终审',
		'sites_push' => '推送至批量分站', 
		'cms_sites_push' => '推送数据到分站', 
		'clone' => '签发到多个栏目',
		/*'view_to_html' => '内容页静态',*/
		'setviews' => '设置浏览量',
		'level' => '设置权重',
		'attribute' => '设置内容属性',
		'create_time' => '设置发布时间',
		'filter_word' => '忽略系统敏感词检测',
		'content_censor' => '忽略大数据内容检测',	
		'comment' => '评论管理',		
		'post_comment' => '发表评论',
		'verify_comment' => '审核评论',
		'delete_comment' => '删除评论',
	),
	
	//可以用于积分规则的action
	'credit_rule_actions' => array(
		'verify' => '审核通过',
		'delete' => '被删除'
	),
	//忽略项
	
);
