-- <?php exit;?>

CREATE TABLE `p8_` (
  `id` int(10) unsigned NOT NULL,
  `model` varchar(20) NOT NULL default '',
  `cid` smallint(5) unsigned NOT NULL DEFAULT '0',
  `uid` mediumint(8) unsigned NOT NULL default '0',
  `username` varchar(50) NOT NULL default '',
  `title` varchar(500) NOT NULL default '',
  `title_color` varchar(7) NOT NULL default '',
  `title_bold` tinyint(1) NOT NULL default '0',
  `sub_title` varchar(120) NOT NULL DEFAULT '',
  `frame` varchar(500) NOT NULL default '',
  `verify_frame` varchar(255) NOT NULL default '',
  `attachment_pdf` varchar(255) NOT NULL default '',
  `url` varchar(512) NOT NULL default '',
  `attributes` varchar(40) NOT NULL DEFAULT '',
  `summary` varchar(1000) NOT NULL default '',
  `source` varchar(120) NOT NULL default '',
  `author` varchar(20) NOT NULL default '',
  `author_x` varchar(20) NOT NULL default '',
  `author_y` varchar(20) NOT NULL default '',
  `author_z` varchar(20) NOT NULL default '',
  `authority` varchar(255) NOT NULL default '',
  `editer` varchar(20) NOT NULL default '',
  `keywords` varchar(100) NOT NULL default '',
  `verified` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `verifier` varchar(50) NOT NULL default '',
  `verify_time` int(10) unsigned NOT NULL default '0',
  `timestamp` int(10) unsigned NOT NULL DEFAULT '0',
  `create_time` int(10) unsigned NOT NULL default '0',
  `list_order` int(10) unsigned NOT NULL DEFAULT '0',
  `update_time` int(10) unsigned NOT NULL DEFAULT '0',
  `pages` smallint(5) unsigned NOT NULL default '1',
  `html_view_url_rule` varchar(80) NOT NULL default '',
  `template` varchar(30) NOT NULL default '',
  `views` mediumint(8) unsigned NOT NULL DEFAULT '0',
  `score` tinyint(3) NOT NULL DEFAULT '0',
  `level` tinyint(1) unsigned NOT NULL default '0',
  `level_time` int(10) unsigned NOT NULL default '0',
  `comments` mediumint(8) unsigned NOT NULL DEFAULT '0',
  `seo_keywords` varchar(100) NOT NULL DEFAULT '',
  `seo_description` varchar(200) NOT NULL DEFAULT '',
  `label_postfix` varchar(50) NOT NULL DEFAULT '',
  `config` varchar(1255) NOT NULL DEFAULT '',
  `custom_a` VARCHAR(255) NOT NULL DEFAULT '',
  `custom_b` VARCHAR(255) NOT NULL DEFAULT '',
  `custom_c` VARCHAR(255) NOT NULL DEFAULT '',
  `custom_d` VARCHAR(255) NOT NULL DEFAULT '',
  `custom_e` VARCHAR(255) NOT NULL DEFAULT '',
  PRIMARY KEY  (`id`),
  KEY `cid` (`cid`,`list_order`),
  KEY `cid_id` (`cid`,`id`),
  KEY `level` (`level`,`list_order`),
  KEY `uid` (`uid`)
)ENGINE=MyISAM  DEFAULT CHARSET=utf8;

CREATE TABLE `p8_addon` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `iid` int(10) unsigned NOT NULL DEFAULT '0',
  `page` smallint(5) unsigned NOT NULL DEFAULT '0',
  `addon_title` varchar(40) NOT NULL DEFAULT '',
  `addon_frame` varchar(100) NOT NULL DEFAULT '',
  `addon_summary` varchar(1080) NOT NULL DEFAULT '',
  `ip` char(15) NOT NULL DEFAULT '',
  `last_update_ip` char(15) NOT NULL DEFAULT '',
  `timestamp` int(10) unsigned NOT NULL DEFAULT '0',
  `custom_f` varchar(255) NOT NULL DEFAULT '',
  `custom_g` varchar(255) NOT NULL DEFAULT '',
  `custom_h` varchar(255) NOT NULL DEFAULT '',
  `custom_i` varchar(255) NOT NULL DEFAULT '',
  `custom_j` varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY  (`id`),
  KEY `iid` (`iid`,`page`)
)ENGINE=MyISAM  DEFAULT CHARSET=utf8;
