<?php
return array(
	'id' => 'ID',
	'department' => '部门ID',
	'type' => '问题类别ID',
	'visual' => '是否公开',
	'number' => '序列号',
	'uid' => '用户ID',
	'username' => '用户名',
	'code' => '查询码',
	'gender' => '性别',
	'age' => '年龄',
	'phone' => '联系电话',
	'ip' => 'IP',
	'email' => '电子邮件',
	'profession' => '职业',
	'education' => '',
	'address' => '联系地址',
	'title' => '主题',
	'create_time' => '创建时间',
	'update_time' => '更新时间',
	'status' => '状态',
	'status_change_time' => '状态变更时间',
	'askable' => '可提问',
	'log' => '操作日志',
	'solve_time' => '解决时间',
	'solve_uid' => '解决用户ID',
	'solve_department' => '解决部门ID',
	'solve_name' => '解决用户',
	'comment' => '点评',
	'comment_time' => '点评时间',
);?>
