-- <?php exit;?>

CREATE TABLE `p8_` (
  `id` int(10) unsigned NOT NULL,
  `model` varchar(20) NOT NULL DEFAULT '',
  `cid` smallint(5) unsigned NOT NULL,
  `uid` mediumint(8) unsigned NOT NULL DEFAULT '0',
  `username` varchar(20) NOT NULL DEFAULT '',
  `title` varchar(500) NOT NULL DEFAULT '',
  `title_color` varchar(7) NOT NULL DEFAULT '',
  `title_bold` tinyint(1) NOT NULL DEFAULT '0',
  `sub_title` varchar(120) NOT NULL DEFAULT '',
  `site` varchar(50) NOT NULL DEFAULT '',
  `frame` varchar(500) NOT NULL DEFAULT '',
  `verify_frame` varchar(555) NOT NULL DEFAULT '',
  `attachment_pdf` varchar(555) NOT NULL DEFAULT '',
  `url` varchar(512) NOT NULL DEFAULT '',
  `attributes` varchar(40) NOT NULL DEFAULT '',
  `summary` varchar(1255) NOT NULL DEFAULT '',
  `source` varchar(120) NOT NULL DEFAULT '',
  `author` varchar(20) NOT NULL DEFAULT '',
  `author_x` varchar(20) NOT NULL default '',
  `author_y` varchar(20) NOT NULL default '',
  `author_z` varchar(20) NOT NULL default '',
  `authority` varchar(255) NOT NULL,
  `editer` varchar(20) NOT NULL DEFAULT '',
  `keywords` varchar(1100) NOT NULL DEFAULT '',
  `verified` tinyint(1) unsigned NOT NULL,
  `verifier` tinyint(1) unsigned NOT NULL,
  `timestamp` int(10) unsigned NOT NULL,
  `create_time` int(10) unsigned NOT NULL DEFAULT '0',
  `list_order` int(10) unsigned NOT NULL,
  `update_time` int(10) unsigned NOT NULL,
  `pages` smallint(5) unsigned NOT NULL DEFAULT '1',
  `html_view_url_rule` varchar(80) NOT NULL DEFAULT '',
  `template` varchar(30) NOT NULL DEFAULT '',
  `views` mediumint(8) unsigned NOT NULL,
  `score` tinyint(3) NOT NULL DEFAULT '0',
  `level` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `level_time` int(10) unsigned NOT NULL DEFAULT '0',
  `comments` mediumint(8) unsigned NOT NULL,
  `seo_keywords` varchar(100) NOT NULL DEFAULT '',
  `seo_description` varchar(200) NOT NULL DEFAULT ''
  `label_postfix` varchar(50) NOT NULL,
  `config` varchar(1255) NOT NULL,
  `custom_a` varchar(255) NOT NULL,
  `custom_b` varchar(255) NOT NULL,
  `custom_c` varchar(255) NOT NULL,
  `custom_d` varchar(255) NOT NULL,
  `custom_e` varchar(255) NOT NULL,
  PRIMARY KEY  (`id`),
  KEY `cid` (`cid`,`list_order`),
  KEY `cid_id` (`cid`,`id`),
  KEY `level` (`level`,`list_order`),
  KEY `uid` (`uid`)
)ENGINE=MyISAM  DEFAULT CHARSET=utf8;

CREATE TABLE `p8_addon` (
  `id` int(10) unsigned NOT NULL auto_increment,
  `iid` int(10) unsigned NOT NULL,
  `site` varchar(50) NOT NULL DEFAULT '',
  `page` smallint(5) unsigned NOT NULL,
  `addon_title` varchar(40) NOT NULL default '',
  `addon_frame` varchar(100) NOT NULL default '',
  `addon_summary` varchar(1080) NOT NULL default '',
  `ip` char(15) NOT NULL default '',
  `last_update_ip` char(15) NOT NULL default '',
  `timestamp` int(10) unsigned NOT NULL,
  `custom_f` VARCHAR( 255 ) NOT NULL,
  `custom_g` VARCHAR( 255 ) NOT NULL,
  `custom_h` VARCHAR( 255 ) NOT NULL,
  `custom_i` VARCHAR( 255 ) NOT NULL,
  `custom_j` VARCHAR( 255 ) NOT NULL,
  PRIMARY KEY  (`id`),
  KEY `iid` (`iid`,`page`)
)ENGINE=MyISAM  DEFAULT CHARSET=utf8;
